# docker-compose.yml
version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: himakeu_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: himakeu_transactions
      MYSQL_USER: himakeu_user
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/mysql:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password

  postgres:
    image: postgres:15
    container_name: himakeu_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: himakeu_master
      POSTGRES_USER: himakeu_user
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/postgresql:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
  postgres_data: